apiVersion: v1
kind: Service
metadata:
  name: $PROJECT_NAME-service
spec:
  selector:
    app: $PROJECT_NAME
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
